# Generated by Django 3.1.1 on 2021-02-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Konigstrasse 3', max_length=75),
            preserve_default=False,
        ),
    ]
